package de.uniluebeck.itm.kma;

import java.awt.event.ActionEvent;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Simple Media Converter application, as requested in
 * KMA-Lab homework 1.
 *
 * @author seidel
 */
public class MediaConverterUI extends JFrame
{
  /** Logger object for debug output */
  private static final Logger LOGGER = LoggerFactory.getLogger(MediaConverterUI.class);

  /** Input file object */
  private File inputFile = null;

  /** FileAnalyzer object */
  private FileAnalyzer fileAnalyzer = null;

  /**
   * Create Media Converter user interface.
   */
  public MediaConverterUI()
  {
    initComponents();

    fileAnalyzer = new FileAnalyzer(LogPane);
  }

  /**
   * This method is called from within the constructor to initialize
   * the form.
   *
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the NetBeans form editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    InputFileChooser = new javax.swing.JFileChooser();
    OutputFileChooser = new javax.swing.JFileChooser();
    InputPanel = new javax.swing.JPanel();
    SelectFileButton = new javax.swing.JButton();
    FileNameTextField = new javax.swing.JTextField();
    LogPanel = new javax.swing.JPanel();
    ScrollPane = new javax.swing.JScrollPane();
    LogPane = new javax.swing.JTextPane();
    FileFormatPanel = new javax.swing.JPanel();
    FileFormatComboBox = new javax.swing.JComboBox();
    VolumePanel = new javax.swing.JPanel();
    VolumeSlider = new javax.swing.JSlider();
    MenuBar = new javax.swing.JMenuBar();
    FileMenu = new javax.swing.JMenu();
    Open = new javax.swing.JMenuItem();
    Save = new javax.swing.JMenuItem();
    Separator = new javax.swing.JPopupMenu.Separator();
    Exit = new javax.swing.JMenuItem();

    InputFileChooser.setDialogTitle("Open file...");
    InputFileChooser.setFileFilter(new MediaFileFilter());

    OutputFileChooser.setDialogTitle("Save file as...");
    OutputFileChooser.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
    OutputFileChooser.setFileFilter(new MediaFileFilter());

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Media Converter");
    setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    setLocationByPlatform(true);
    setMinimumSize(new java.awt.Dimension(793, 458));

    InputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Input file"));

    SelectFileButton.setText("Select file...");
    SelectFileButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        SelectFileButtonActionPerformed(evt);
      }
    });

    FileNameTextField.setEditable(false);

    javax.swing.GroupLayout InputPanelLayout = new javax.swing.GroupLayout(InputPanel);
    InputPanel.setLayout(InputPanelLayout);
    InputPanelLayout.setHorizontalGroup(
      InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(InputPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(FileNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
        .addGap(35, 35, 35)
        .addComponent(SelectFileButton)
        .addContainerGap())
    );
    InputPanelLayout.setVerticalGroup(
      InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(InputPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(FileNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(SelectFileButton))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    LogPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Summary"));

    LogPane.setEditable(false);
    ScrollPane.setViewportView(LogPane);

    javax.swing.GroupLayout LogPanelLayout = new javax.swing.GroupLayout(LogPanel);
    LogPanel.setLayout(LogPanelLayout);
    LogPanelLayout.setHorizontalGroup(
      LogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(LogPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
        .addContainerGap())
    );
    LogPanelLayout.setVerticalGroup(
      LogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(LogPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
        .addContainerGap())
    );

    FileFormatPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Change file format"));

    FileFormatComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    javax.swing.GroupLayout FileFormatPanelLayout = new javax.swing.GroupLayout(FileFormatPanel);
    FileFormatPanel.setLayout(FileFormatPanelLayout);
    FileFormatPanelLayout.setHorizontalGroup(
      FileFormatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(FileFormatPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(FileFormatComboBox, 0, 323, Short.MAX_VALUE)
        .addContainerGap())
    );
    FileFormatPanelLayout.setVerticalGroup(
      FileFormatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(FileFormatPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(FileFormatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    VolumePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Adjust volume"));

    javax.swing.GroupLayout VolumePanelLayout = new javax.swing.GroupLayout(VolumePanel);
    VolumePanel.setLayout(VolumePanelLayout);
    VolumePanelLayout.setHorizontalGroup(
      VolumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(VolumePanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(VolumeSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        .addContainerGap())
    );
    VolumePanelLayout.setVerticalGroup(
      VolumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(VolumePanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(VolumeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(20, Short.MAX_VALUE))
    );

    FileMenu.setText("File");

    Open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
    Open.setText("Open file...");
    Open.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        OpenActionPerformed(evt);
      }
    });
    FileMenu.add(Open);

    Save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
    Save.setText("Save file as...");
    Save.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        SaveActionPerformed(evt);
      }
    });
    FileMenu.add(Save);
    FileMenu.add(Separator);

    Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
    Exit.setText("Exit");
    Exit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ExitActionPerformed(evt);
      }
    });
    FileMenu.add(Exit);

    MenuBar.add(FileMenu);

    setJMenuBar(MenuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(LogPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(InputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(FileFormatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(VolumePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(FileFormatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(VolumePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(18, 18, 18)
        .addComponent(LogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * Action performed, when the "Select file..." button is clicked.
   * We just call OpenFile() in this case, so we do not have to
   * maintain multiple methods for input file handling.
   * 
   * @param evt ActionEvent
   */
    private void SelectFileButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SelectFileButtonActionPerformed
    {//GEN-HEADEREND:event_SelectFileButtonActionPerformed
      this.OpenFile(evt);
    }//GEN-LAST:event_SelectFileButtonActionPerformed

  /**
   * Action performed, when "Exit" item is selected in file menu.
   * This will close the application and return status code 0.
   * 
   * @param evt ActionEvent
   */
    private void ExitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ExitActionPerformed
    {//GEN-HEADEREND:event_ExitActionPerformed
      System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

  /**
   * Action performed, when "Open file..." item is selected in
   * the file menu. Again we just call OpenFile() for better
   * code maintenance.
   *
   * @param evt ActionEvent
   */
    private void OpenActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_OpenActionPerformed
    {//GEN-HEADEREND:event_OpenActionPerformed
      this.OpenFile(evt);
    }//GEN-LAST:event_OpenActionPerformed

  /**
   * This method handles action events from the JFileChooser.
   * It checks whether the returned value is a valid file,
   * loads it and starts file analysis.
   *
   * @param event ActionEvent
   */
  private void OpenFile(ActionEvent event)
  {
    // Get return value from JFileChooser
    int returnValue = InputFileChooser.showOpenDialog(this);

    // Did user open a file?
    if (returnValue == JFileChooser.APPROVE_OPTION)
    {
      this.inputFile = InputFileChooser.getSelectedFile();

      // Check whether file exists
      if (!this.inputFile.exists())
      {
        throw new IllegalArgumentException("Selected input file does not exist.");
      }
      else
      {
        // Set input file name in GUI
        FileNameTextField.setText(this.inputFile.getName());

        // Analyse media file
        fileAnalyzer.analyzeMediafile(this.inputFile.getAbsolutePath());
      }
    }
  }

  /**
   * Action performed, when "Save file as..." item is selected in
   * the file menu. If a valid file name is provided, media
   * conversion is done and a summary of the output file is
   * written to the log pane.
   *
   * @param evt ActionEvent
   */
    private void SaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SaveActionPerformed
    {//GEN-HEADEREND:event_SaveActionPerformed
      int returnValue = OutputFileChooser.showOpenDialog(this);

      // Check whether valid file name was provided
      if (returnValue == JFileChooser.APPROVE_OPTION)
      {
        // Create output file
        File outputFile = new File(OutputFileChooser.getSelectedFile().getAbsolutePath());

        // TODO write output file
      }
    }//GEN-LAST:event_SaveActionPerformed

  /**
   * Media Converter application.
   *
   * @param args Command line arguments
   */
  public static void main(String args[])
  {
    // Launch application
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new MediaConverterUI().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuItem Exit;
  private javax.swing.JComboBox FileFormatComboBox;
  private javax.swing.JPanel FileFormatPanel;
  private javax.swing.JMenu FileMenu;
  private javax.swing.JTextField FileNameTextField;
  private javax.swing.JFileChooser InputFileChooser;
  private javax.swing.JPanel InputPanel;
  private javax.swing.JTextPane LogPane;
  private javax.swing.JPanel LogPanel;
  private javax.swing.JMenuBar MenuBar;
  private javax.swing.JMenuItem Open;
  private javax.swing.JFileChooser OutputFileChooser;
  private javax.swing.JMenuItem Save;
  private javax.swing.JScrollPane ScrollPane;
  private javax.swing.JButton SelectFileButton;
  private javax.swing.JPopupMenu.Separator Separator;
  private javax.swing.JPanel VolumePanel;
  private javax.swing.JSlider VolumeSlider;
  // End of variables declaration//GEN-END:variables
}
